### PR TITLE
is_first_col/ is_first_row are deprecated in Matplotlib 3.4

### PR DESCRIPTION
**Pull request by mr-superonion**
Hello, 

The is_first_col and is_first_row have been deprecated in Matplotlib 3.4;
see the link below:
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#subplot-related-attributes-and-methods

### CODE REVIEW

**Comment by ejhigson** [comment]
Hi @mr-superonion - thank you very much for the pull request and for helping fix this deprecation!

Your change seems to have made some of the tests fail at https://app.travis-ci.com/github/mr-superonion/nestcheck/builds/260124842. Please can you edit your PR to these tests pass? I'm happy to remove support for some of the older versions like 2.7 and 3.4 if there is some annoying issue with the tests as these versions are now very old, but the tests for 3.7 should pass.

Many thanks,
Ed

**Comment by mr-superonion** [comment]
Hello, 
It seems to me that there are more warning in python 3.7+ than 3:
https://github.com/ejhigson/nestcheck/blob/3d43d0e6adef6d0aab885fe12133d0106d84db93/tests/test_core.py#L574
which makes the tests fail.

**Comment by mr-superonion** [comment]
Here is one of the warning:
```
nestcheck/error_analysis.py:416: RuntimeWarning: ks_2samp: Exact calculation unsuccessful. Switching to method=asymp.
```
I guess this is not going to cause any error in the result, am I correct?
Therefore, I set the number of warning to 5 in the unit tests.

Also, I force to use pandas<1.2.0; otherwise there are more warnings.

**Comment by ejhigson** [comment]
Hi @mr-superonion - thank you very much for this update! In retrospect I think the test of the number of warnings is not a good idea given the way this changes as package versions increase (my fault), and regardless this test is not very important anyway and can be skipped. All the changes seem good except forcing pandas to use an old version, which seems bad and not worth it to pass the annoying warnings test.

Please can you remove the change to the pandas version requirement in setup.py, and change the test of the warnings to assert that there are >= 3 warnings (or even >= 1 warning)? This seems quicker than removing the test, and if extra warnings arrive or go away later then the test won't break. With this change, if all the tests pass, then I'll merge the pull request.

> nestcheck/error_analysis.py:416: RuntimeWarning: ks_2samp: Exact calculation unsuccessful. Switching to method=asymp.
> I guess this is not going to cause any error in the result, am I correct?
I don't think so - this warning is from scipy.stats.ks_2samp and it should still give reasonable results.

Thank you very much for your contribution to nestcheck and sorry for the extra steps here! I appreciate your help with this.

Ed

**Comment by ejhigson** [comment]
> Please can you remove the change to the pandas version requirement in setup.py, and change the test of the warnings to assert that there are >= 3 warnings (or even >= 1 warning)? This seems quicker than removing the test, and if extra warnings arrive or go away later then the test won't break. With this change, if all the tests pass, then I'll merge the pull request.

Hi @mr-superonion - are you OK with these changes? If so please update the PR and I will merge. Once again thank you very much for your contributions! :)

**Comment by mr-superonion** [comment]
Sorry for the late reply. Does it look OK now?

**Comment by ejhigson** [comment]
Looks good, thank you very much for this!

**Pull request merged**
